version: 2

models:
  - name: stg_customers
    config:
      tags: ["staging", "PII"]
    columns:
      - name: customer_id

        tests:
          - unique:
              config:
                tags:
                  - GPT
              meta:
                description: This is a primary key so should be unique
          - not_null:
              config:
                tags:
                  - GPT
              meta:
                description: This is a primary key so should be unique
  - name: stg_orders
    config:
      tags: ["staging", "finance"]
    columns:
      - name: order_id
        tests:
          - unique:
              config:
                tags:
                  - GPT
              meta:
                description: This is a primary key so should be unique
          - not_null:
              config:
                tags:
                  - GPT
              meta:
                description: This is a primary key so should be unique
      - name: status

  - name: stg_payments
    config:
      tags: ["staging", "finance"]
    columns:
      - name: payment_id
        tests:
          - unique:
              config:
                tags:
                  - GPT
              meta:
                description: This is a primary key so should be unique
          - not_null:
              config:
                tags:
                  - GPT
              meta:
                description: This is a primary key so should be unique
      - name: payment_method

  - name: stg_signups
    config:
      tags: ["staging", "PII"]
    columns:
      - name: signup_id
        tests:
          - unique:
              config:
                tags:
                  - GPT
              meta:
                description: This is a primary key so should be unique
          - not_null:
              config:
                tags:
                  - GPT
              meta:
                description: This is a primary key so should be unique
      - name: customer_email
